## https://starship.rs/config/

[line_break]
disabled = true

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_commit]
tag_disabled = false

[git_status]
conflicted = "âš”ï¸${count}"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "?${count}"
stashed = "ğŸ“¦${count}"
modified = "ğŸ“${count}"
staged = "ğŸ—ƒï¸ ${count}"
renamed = "ğŸ“›${count}"
deleted = "âœ˜${count}"
# format = "$all_status$ahead_behind"

## Languages
[package]
disabled = true

[rust]
format = "[$symbol($version )]($style)"


## Clouds

[aws]
disabled = false

[gcloud]
disabled = true